web:
  extends:
    file: common.yml
    service: web
  volumes:
   - ..:/code:ro
  environment:
    - NODE_PATH=/app/node_modules
  # entrypoint can't see volumes e.g. /code for some reason
  # for now clear out entrypoint and use command for development
  entrypoint: []
  command: /env/bin/python /code/main.py
