web:
  extends:
    file: common.yml
    service: web
  volumes:
   - ..:/code:ro
#  links:
#   - redis
  environment:
    - NODE_PATH=/app/node_modules
#    - REDIS_HOST=redis
  command: /env/bin/python /code/main.py
#redis:
#  image: redis
